### ISSUE TITLE
edit NAMESPACE or DESCRIPTION

### ISSUE THREAD

**Issue by stuartWagenius** [stuartWagenius/mateable#8]
We got the below warning & recommendation when we submitted to CRAN. We added to namespace, but a better solution might be editing the description. Also, how do we avoid this warning in the future?

proximity: no visible binding for global variable 'median'
simulateScene: no visible global function definition for 'rnorm'
simulateScene: no visible global function definition for 'runif'
synchrony: no visible binding for global variable 'median'
Undefined global functions or variables:
  abline aggregate arrows axis colorRampPalette density dist hist image
  legend lines median mtext palette par plot plot.default points rnorm
  runif sd segments text title
Consider adding
  importFrom("grDevices", "colorRampPalette", "palette")
  importFrom("graphics", "abline", "arrows", "axis", "hist", "image",
             "legend", "lines", "mtext", "par", "plot", "plot.default",
             "points", "segments", "text", "title")
  importFrom("stats", "aggregate", "density", "dist", "median", "rnorm",
             "runif", "sd")
to your NAMESPACE file.

**Comment by danhan52** [comment]
Commit ef70828 on 23 Mar 2016 fixes this issue. I added in statements that import the entirety of grDevices, graphics, and stats so we can use anything from those without having to import specific functions.
